version: '3'

services:
  database:
    image: postgres:12.2
    volumes:
      - ../data/postgre/data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: fragalysis
      POSTGRES_USER: fragalysis
      POSTGRES_DB: frag
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
    - "5432:5432"
  graph:
    container_name: neo4j
    image: informaticsmatters/fragnet-test:3.5.25-xchem-combi-sample-2021-02
    ports:
# Comment these two out in produciton
      - "7474:7474"
      - "7687:7687"
    ulimits:
      nofile:
        soft: 40000
        hard: 40000
    environment:
      GRAPH_PASSWORD: test123
      CYPHER_PRE_NEO4J_SLEEP: 0
      NEO4J_dbms_memory_pagecache_size: 4G
  web:
    container_name: web_dock
    image: xchem/fragalysis-stack:latest
    command: /bin/bash /code/launch-stack.sh
    volumes:
      - ../data/logs:/code/logs/
      - ../data/media:/code/media/
      - ../fragalysis-frontend:/code/frontend
    ports:
      - "8080:80"
    environment:
      POSTGRESQL_DATABASE: frag
      POSTGRESQL_USER: fragalysis
      POSTGRESQL_PASSWORD: fragalysis
      POSTGRESQL_HOST: database
      POSTGRESQL_PORT: 5432
      NEO4J_AUTH: neo4j/test123
    depends_on:
      - database
      - graph
  loader:
    container_name: loader
    image: loader:latest
    volumes:
      - ../data/input:/fragalysis
      - ../data/media:/code/media
    environment:
      POSTGRESQL_DATABASE: frag
      POSTGRESQL_USER: fragalysis
      POSTGRESQL_PASSWORD: fragalysis
      POSTGRESQL_HOST: database
      POSTGRESQL_PORT: 5432
      DATA_ORIGIN: EXAMPLE
    depends_on:
      - database
